services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:18.0
    depends_on:
      - postgres
    ports:
      - "18070:8069"
    environment:
      HOST: postgres
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - ./data:/var/lib/odoo
    restart: unless-stopped
    command: >
      odoo
      --dev xml
      --database odoo_demo_db
      --init l10n_do,l10n_do_accounting
      --without-demo=all
      --stop-after-init
      && odoo
